services:

  ####Drupal10 ####################################################
  commercenest:
    image: ${COMMERCENEST_IMAGE_TAG:-lawxen/drupal:d10-php82}
    volumes:
      - ./html:/var/www/html
    container_name: commercenest
    ports:
      - 80:80
    networks:
      - backend

  ### Mariadb Container #######################################
  commercenest-db:
    image: mariadb:latest
    volumes:
      - ./mysql:/var/lib/mysql
      - ./config/mysql/my.cnf:/etc/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3306"
    container_name: commercenest-db
    restart: always
    networks:
      - backend

### Redis Container #########################################
  # redis:
  #   image: latest
  #   container_name: redis
  #   environment:
  #     - REDIS_PASSWORD=c4200bc580
  #     - ALLOW_EMPTY_PASSWORD=no
  #   ports:
  #     - "6379"
  #   networks:
  #     - backend

### Network ###############################################
networks:
  backend:
    driver: "bridge"
